deeptime-ml/deeptime

.circleci/config.yml
devtools/conda-recipe/meta.yaml
devtools/conda-recipe/run_test.py
pyproject.toml
setup.py
sktime/covariance/util/covar_c/covartools.py
tests/decomposition/test_koopman_reweighting.py

add circle ci support, fixed some minor issues.

---

sktime/markovprocess/markov_state_model.py
sktime/markovprocess/pcca.py
sktime/markovprocess/reactive_flux.py
tests/markovprocess/test_reactive_flux.py

Pcca and reactive flux estimator/model pattern

---

sktime/markovprocess/__init__.py
sktime/markovprocess/chapman_kolmogorov_validator.py
sktime/markovprocess/markov_state_model.py
sktime/markovprocess/pcca.py
sktime/markovprocess/reactive_flux.py
tests/base/test_sklearn_compat.py
tests/markovprocess/test_msm.py
tests/markovprocess/test_reactive_flux.py

Revert pcca, tpt estimator|model pattern

---

sktime/decomposition/tica.py
sktime/markov/hmm/hidden_markov_model.py
sktime/markov/msm/augmented_msm.py
sktime/markov/msm/markov_state_model.py
sktime/markov/util.py
sktime/numeric/eigen.py
tests/decomposition/test_vamp.py
tests/markov/hmm/test_mlhmm.py
tests/markov/msm/test_msm_basic_properties.py
tests/numeric/test_utils.py

- fixed msm propagate for sparse transition matrices
- thorough testing for numeric module
- minor fixes/improvements

testing and fix in msm

---

AUTHORS
docs/source/_templates/class_nomodule.rst
docs/source/api/index_sindy.rst
docs/source/changelog.rst
docs/source/index.rst
docs/source/references.bib
examples/plot_sindy_rossler_attractor.py
sktime/__init__.py
sktime/numeric/__init__.py
sktime/numeric/utils.py
sktime/setup.py
sktime/sindy/__init__.py
sktime/sindy/_sindy.py
sktime/sindy/sindy.py
tests/sindy/test_sindy.py

This pull request provides a simple implementation of the Sparse Identification of Nonlinear Dynamics (SINDy) method for nonlinear model discovery. It includes
* A `SINDy` estimator class for fitting a `SINDyModel` objects to data
* A `SINDyModel` class encapsulating the learned dynamical system
* Tests for the important methods and use-cases
The pull request is not quite complete—I still need to create an example showing how to use the new features—but I figured this was a good place for me to give you, the Scikit-time team, a chance to look at implementation. I tried to use existing sktime code as inspiration, but feel free to edit anything that doesn't conform to your standards or style.
The other thing I'd like to flag is that I wasn't able to test whether the auto-generated …

Sparse Identification of Nonlinear Dynamics

---

sktime/decomposition/dmd.py
sktime/decomposition/koopman.py
sktime/kernels/kernels_torch.py
sktime/numeric/eigen.py
sktime/numeric/slepc.py
tests/decomposition/test_dmd.py
tests/kernels/test_kernels_torch.py
tests/numeric/test_slepc.py

- Vectorize evaluate over batch for torch gaussian
- rank truncation for DMD

Kernels and DMD

---

deeptime/data/__init__.py
deeptime/data/_bickley_simulator.py
deeptime/data/_datasets.py
deeptime/data/_util.py
deeptime/decomposition/__init__.py
deeptime/decomposition/_koopman.py
deeptime/decomposition/_score.py
deeptime/decomposition/_vamp.py
deeptime/kernels/_kernels.py
deeptime/kernels/_kernels_torch.py
deeptime/util/torch.py
deeptime/util/types.py
docs/Makefile
docs/requirements.txt
docs/source/conf.py
docs/source/contents.rst
docs/source/index_examples.rst
examples/datasets/plot_bickley_jet.py
examples/datasets/plot_swissroll_model.py
examples/methods/README.rst
tests/data/test_swissroll.py
tests/data/test_util.py
tests/decomposition/test_tae.py
tests/decomposition/test_vamp.py
tests/decomposition/test_vampnet.py

- TimeLaggedDataset can be constructed with multiple trajectories
- Swissroll example
- Update to kCCA docs
- Added VAMPNets Ala2 example

Datasets and docs

---

deeptime/data/__init__.py
deeptime/data/_datasets.py
deeptime/data/include/systems.h
deeptime/data/src/data_module.cpp
deeptime/decomposition/_cca.py
deeptime/decomposition/_dmd.py
deeptime/decomposition/deep/_vampnet.py
examples/datasets/plot_prinz.py
tests/data/test_prinz.py

Prinz potential

---

deeptime/data/__init__.py
deeptime/data/_datasets.py
deeptime/data/_systems.py
deeptime/data/include/integrator.h
deeptime/data/include/systems.h
deeptime/data/src/data_module.cpp
deeptime/util/__init__.py
examples/datasets/plot_custom_ode.py
examples/datasets/plot_time_quintuple_well.py
examples/datasets/plot_triple_well_1d.py
tests/data/test_cpp_systems.py

Datasets defined in extension code can now generate trajectories from multiple starting points simultaneously, also the system instances are wrapped into python objects which do some type and shape checking, making the api easier to use (thanks @thempel for the hint).

Make dataset bindings more flexible

---

deeptime/markov/hmm/_maximum_likelihood_hmm.py
deeptime/util/platform.py
tests/decomposition/test_tae.py
tests/decomposition/test_vampnet.py

Adds support for tqdm progress bars in HMM estimations

Progress bar support for HMM estimation

---

deeptime/basis/src/basis_bindings.cpp
deeptime/clustering/include/bits/kmeans_bits.h
deeptime/markov/hmm/_bindings/include/OutputModelUtils.h
deeptime/markov/tools/estimation/dense/_bindings/include/sampler.h
deeptime/markov/tools/estimation/sparse/mle/newton/objective_sparse_ops.cpp
deeptime/markov/tools/kahandot/kahandot_module.cpp
devtools/azure-pipelines-linux.yml
devtools/azure-pipelines-osx.yml
devtools/azure-pipelines-win.yml
devtools/conda-recipe/meta.yaml
devtools/conda-recipe/run_test.py
devtools/conda-setup+build.yml
noxfile.py
tests/requirements.txt

should fix compiler error in conda-forge/deeptime-feedstock#16

enable python 3.10 in build matrix

---

deeptime/markov/_transition_counting.py
tests/markov/test_transition_counts.py

fix mapping states back to symbols

---

deeptime/markov/msm/tram/_tram.py
docs/source/index_msm.rst

toc and a bugfix

---

deeptime/markov/hmm/_hidden_markov_model.py
tests/markov/hmm/test_mlhmm.py

HMM method `submodel_disconnect()` was broken, using it resulted in a TypeError.

fix submodel_disconnect and add test

---

CMakeLists.txt
deeptime/clustering/_kmeans.py
deeptime/markov/msm/tram/_tram.py
deeptime/markov/msm/tram/_tram_dataset.py
deeptime/src/include/deeptime/common.h
deeptime/util/__init__.py
deeptime/util/callbacks.py
deeptime/util/platform.py
docs/requirements.txt
docs/source/index_msm.rst
examples/clustering_custom_metric/CMakeLists.txt
examples/clustering_custom_metric/bindings.cpp
examples/methods/plot_tram.py
tests/clustering/test_kmeans.py
tests/markov/msm/test_tram.py
tests/markov/msm/test_tram_datatset.py
tests/requirements.txt
tests/testing_utilities.py

Cluster progress

---

deeptime/markov/msm/tram/_tram_model.py
tests/markov/msm/test_tram.py

Log space sample weights

---

deeptime/markov/msm/tram/_tram_model.py

Make sample weights normalized

---

deeptime/decomposition/deep/_tae.py

Update to TAE so that validation loss is reading from validation_dataloader

Update validation loss on TAE

---

deeptime/markov/msm/tram/_tram_model.py
tests/markov/msm/test_tram_model.py

Fix the calculation of the PMF.

---

deeptime/markov/msm/tram/_tram_dataset.py
deeptime/markov/msm/tram/_tram_model.py
tests/markov/msm/test_tram_datatset.py

Fix shape of empty count models

---

deeptime/markov/msm/tram/_tram.py
deeptime/src/include/deeptime/markov/msm/tram/tram.h
tests/markov/msm/test_tram.py

TRAM still gave a convergence warning if it converged inbetween two callback calls. That is now fixed.

Convergence warning bugfix

---

deeptime/markov/msm/tram/_tram.py
deeptime/markov/msm/tram/_tram_dataset.py
tests/markov/msm/test_tram.py
tests/markov/msm/test_tram_datatset.py

Fix the bug

---

deeptime/markov/msm/tram/_tram.py

remove print

---

deeptime/base_torch.py
deeptime/decomposition/deep/_kvadnet.py
deeptime/decomposition/deep/_tae.py
deeptime/decomposition/deep/_vampnet.py
deeptime/kernels/_kernels_torch.py
deeptime/util/platform.py
deeptime/util/torch.py
devtools/azure-pipelines-linux.yml
devtools/azure-pipelines-osx.yml
devtools/azure-pipelines-win.yml
devtools/conda-setup+build.yml
noxfile.py
pyproject.toml
tests/requirements.txt

Enable python 3.11 in CI pipelines

---

pyproject.toml

restrict scikit-learn version
